[versions]
lombok = "9.2.0"

jakarta-faces = "4.1.2"
jakarta-servlet = "6.1.0"
jakarta-entreprise-cdi = "4.1.0"
jakarta-inject = "2.0.1"
jakarta-transaction = "2.0.1"
jakarta-persistence = "3.1.0"
jakarta-annotation = "3.0.0"

hibernate = "6.6.5.Final"
jaxb-runtime = "4.0.5"
mariadb-java-client = "3.5.1"
jjwt = "0.12.6"
bouncycastle = "1.78.1"

[plugins]
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }

[libraries]
jakarta-faces = { module = "jakarta.faces:jakarta.faces-api", version.ref = "jakarta-faces" }
jakarta-servlet = { module = "jakarta.servlet:jakarta.servlet-api", version.ref = "jakarta-servlet" }
jakarta-entreprise-cdi = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api", version.ref = "jakarta-entreprise-cdi" }
jakarta-inject = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject" }
jakarta-transaction = { module = "jakarta.transaction:jakarta.transaction-api", version.ref = "jakarta-transaction" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta-persistence" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }

hibernate-core = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }
jaxb-runtime = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb-runtime" }
mariadb-java-client = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb-java-client" }

jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

bouncycastle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }

[bundles]
jakarta-apis = [
    "jakarta-faces",
    "jakarta-servlet",
    "jakarta-entreprise-cdi",
    "jakarta-inject",
    "jakarta-transaction",
    "jakarta-persistence",
    "jakarta-annotation"
]

hibernate = [
    "hibernate-core",
    "jaxb-runtime",
    "mariadb-java-client"
]

jjwt = [
    "jjwt-api",
    "jjwt-impl",
    "jjwt-jackson"
]

